#! /bin/sh

CURRENT_KEYMAP=$(~/.i3/script/get_keymap)

# Set _debug to a non-null value for i3-nagbar debugging
_debug=

if [ $CURRENT_KEYMAP = 'us' ]; then
    i___=0
elif [ $CURRENT_KEYMAP = 'bepo' ]; then
    i___=1
elif [ $CURRENT_KEYMAP = 'fr' ]; then
    i___=2
else
    setxkbmap us # Default keymap -> us
    return
fi

i___=$((($i___ + 1) % 3))

case $i___ in
    0)
        setxkbmap us;;
    1)
        setxkbmap fr bepo;;
    2)
        setxkbmap fr;;
esac

if [ $_debug ]; then
    i3-nagbar -m "Current keymap '$CURRENT_KEYMAP' switch to $i___"
fi
